// <auto-generated />
using System;
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(TwoCDbContext))]
    [Migration("20260108141044_InitSchema")]
    partial class InitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Entities.ChartOfAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumChart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subconto1")
                        .HasColumnType("text");

                    b.Property<string>("Subconto2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumChart")
                        .IsUnique();

                    b.ToTable("ChartOfAccount");
                });

            modelBuilder.Entity("DataBase.Entities.Departament", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChartOfAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChartOfAccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("DataBase.Entities.Element", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("CostRealisation")
                        .HasColumnType("numeric");

                    b.Property<int>("CountProduct")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationId")
                        .HasColumnType("text");

                    b.Property<string>("ProductionId")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCostElement")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProductionId");

                    b.ToTable("Element");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartamentId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmountDocument")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("DataBase.Entities.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumOrg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChartOfAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChartOfAccountId");

                    b.ToTable("Organisation");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChartOfAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PlannedCost")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChartOfAccountId");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("Code", "Name")
                        .IsUnique();

                    b.ToTable("Production");
                });

            modelBuilder.Entity("DataBase.Entities.TransactionLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ChartOfAccount2Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChartOfAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationId")
                        .HasColumnType("text");

                    b.Property<decimal>("Subconto1Cred")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subconto1Deb")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subconto2Cred")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subconto2Deb")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChartOfAccount2Id");

                    b.HasIndex("ChartOfAccountId");

                    b.HasIndex("OperationId");

                    b.ToTable("TransactionLog");
                });

            modelBuilder.Entity("DataBase.Entities.Departament", b =>
                {
                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccount")
                        .WithMany("Departament")
                        .HasForeignKey("ChartOfAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChartOfAccount");
                });

            modelBuilder.Entity("DataBase.Entities.Element", b =>
                {
                    b.HasOne("DataBase.Entities.Operation", "Operation")
                        .WithMany("Element")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataBase.Entities.Production", "Production")
                        .WithMany("Elements")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operation");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.HasOne("DataBase.Entities.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId");

                    b.HasOne("DataBase.Entities.Organisation", "Organisation")
                        .WithMany("Operation")
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Departament");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("DataBase.Entities.Organisation", b =>
                {
                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccount")
                        .WithMany("Organisation")
                        .HasForeignKey("ChartOfAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChartOfAccount");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccount")
                        .WithMany("Production")
                        .HasForeignKey("ChartOfAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBase.Entities.Departament", "Departament")
                        .WithMany("Production")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChartOfAccount");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("DataBase.Entities.TransactionLog", b =>
                {
                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccount2")
                        .WithMany("TransactionLog2")
                        .HasForeignKey("ChartOfAccount2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccount")
                        .WithMany("TransactionLog1")
                        .HasForeignKey("ChartOfAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBase.Entities.Operation", "Operation")
                        .WithMany("TransactionLog")
                        .HasForeignKey("OperationId");

                    b.Navigation("ChartOfAccount");

                    b.Navigation("ChartOfAccount2");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("DataBase.Entities.ChartOfAccount", b =>
                {
                    b.Navigation("Departament");

                    b.Navigation("Organisation");

                    b.Navigation("Production");

                    b.Navigation("TransactionLog1");

                    b.Navigation("TransactionLog2");
                });

            modelBuilder.Entity("DataBase.Entities.Departament", b =>
                {
                    b.Navigation("Production");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.Navigation("Element");

                    b.Navigation("TransactionLog");
                });

            modelBuilder.Entity("DataBase.Entities.Organisation", b =>
                {
                    b.Navigation("Operation");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
