// <auto-generated />
using System;
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(TwoCDbContext))]
    [Migration("20260119154409_AgentDeleted")]
    partial class AgentDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Entities.ChartOfAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumChart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subconto1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subconto2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NumChart")
                        .IsUnique();

                    b.ToTable("ChartOfAccounts");
                });

            modelBuilder.Entity("DataBase.Entities.Departament", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departaments");
                });

            modelBuilder.Entity("DataBase.Entities.Element", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("CostRealisation")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("CountProduct")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationId")
                        .HasColumnType("text");

                    b.Property<string>("ProductionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProductionId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.DepartamentHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DepartamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.ToTable("DepartamentHistories");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.OrganisationHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumOrg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ValidFrom");

                    b.ToTable("OrganisationHistories");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.ProductionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DepartamentId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PlannedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.ToTable("ProductionHistories");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartamentId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameDocument")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TotalAmountDocument")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateOperation");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("Type", "DateOperation");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("DataBase.Entities.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumOrg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumOrg")
                        .IsUnique();

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DepartamentId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PlannedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartamentId");

                    b.HasIndex("Code", "Name")
                        .IsUnique();

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("DataBase.Entities.TransactionLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ChartOfAccountCredId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChartOfAccountDebId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOperation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperationId")
                        .HasColumnType("text");

                    b.Property<decimal>("Subconto1Cred")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Subconto1Deb")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Subconto2Cred")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Subconto2Deb")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DateOperation");

                    b.HasIndex("OperationId");

                    b.HasIndex("ChartOfAccountCredId", "DateOperation");

                    b.HasIndex("ChartOfAccountDebId", "DateOperation");

                    b.ToTable("TransactionLogs");
                });

            modelBuilder.Entity("DataBase.Entities.Element", b =>
                {
                    b.HasOne("DataBase.Entities.Operation", "Operation")
                        .WithMany("Element")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataBase.Entities.Production", "Production")
                        .WithMany("Elements")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operation");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.DepartamentHistory", b =>
                {
                    b.HasOne("DataBase.Entities.Departament", "Departament")
                        .WithMany("DepartamentHistories")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.OrganisationHistory", b =>
                {
                    b.HasOne("DataBase.Entities.Organisation", "Organisation")
                        .WithMany("OrganisationHistories")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("DataBase.Entities.HistoriesModel.ProductionHistory", b =>
                {
                    b.HasOne("DataBase.Entities.Production", "Production")
                        .WithMany("ProductionHistories")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.HasOne("DataBase.Entities.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId");

                    b.HasOne("DataBase.Entities.Organisation", "Organisation")
                        .WithMany("Operation")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departament");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.HasOne("DataBase.Entities.Departament", "Departament")
                        .WithMany("Productions")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("DataBase.Entities.TransactionLog", b =>
                {
                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccountCred")
                        .WithMany("TransactionLogCred")
                        .HasForeignKey("ChartOfAccountCredId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataBase.Entities.ChartOfAccount", "ChartOfAccountDeb")
                        .WithMany("TransactionLogDeb")
                        .HasForeignKey("ChartOfAccountDebId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataBase.Entities.Operation", "Operation")
                        .WithMany("TransactionLog")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChartOfAccountCred");

                    b.Navigation("ChartOfAccountDeb");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("DataBase.Entities.ChartOfAccount", b =>
                {
                    b.Navigation("TransactionLogCred");

                    b.Navigation("TransactionLogDeb");
                });

            modelBuilder.Entity("DataBase.Entities.Departament", b =>
                {
                    b.Navigation("DepartamentHistories");

                    b.Navigation("Productions");
                });

            modelBuilder.Entity("DataBase.Entities.Operation", b =>
                {
                    b.Navigation("Element");

                    b.Navigation("TransactionLog");
                });

            modelBuilder.Entity("DataBase.Entities.Organisation", b =>
                {
                    b.Navigation("Operation");

                    b.Navigation("OrganisationHistories");
                });

            modelBuilder.Entity("DataBase.Entities.Production", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("ProductionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
